# IBM Developer Skills Network

## 2D Numpy in Python

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# Create a list
a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [3]:
# Cast list to numpy array
A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [4]:
A.ndim

2

In [5]:
A.shape

(3, 3)

In [6]:
A.size  # total element

9

## Access different elements of a Numpy Array

In [7]:
A[1, 2]

23

In [8]:
A[1][2]  # same result

23

In [9]:
A[0][0:2]

array([11, 12])

In [10]:
A[0:2, 2]

array([13, 23])

In [12]:
X = np.array([[1,0], [0,1]])
X

array([[1, 0],
       [0, 1]])

In [13]:
Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [14]:
Z = X + Y
Z

array([[3, 1],
       [1, 3]])

In [15]:
Z = 2 * Y
Z

array([[4, 2],
       [2, 4]])

In [17]:
Z = X * Y
Z

array([[2, 0],
       [0, 2]])

In [18]:
A = np.array([[0, 1, 1], [1, 0, 1]])
A

array([[0, 1, 1],
       [1, 0, 1]])

In [19]:
B = np.array([[1, 1], [1, 1], [-1, 1]])
B

array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

In [20]:
# Calculate the dot product

Z = np.dot(A,B)
Z

array([[0, 2],
       [0, 2]])

In [21]:
np.sin(Z)

array([[0.        , 0.90929743],
       [0.        , 0.90929743]])

In [23]:
# Transpose matrix
C = np.array([[1,1],[2,2],[3,3]])
C.T

array([[1, 2, 3],
       [1, 2, 3]])